// Just array of pages
// TODO make an object or map
export const adminPages = [
    "/admin/default.aspx",
    "/admin/campaigns/portfolios.aspx",
    "/Admin/Libraries/GlobalImageLibrary.aspx",
    "/Admin/Libraries/GlobalFulfillmentLibrary.aspx",
    "/Admin/Libraries/GlobalFormCategories.aspx",
    "/Admin/Libraries/Snippets",
    "/Admin/Libraries/GlobalScriptCategories.aspx",
    "/Admin/Integration/GlobalServerScriptletCategories.aspx",
    "/Admin/Libraries/Widgets",
    "/Admin/Libraries/GlobalEmailTemplateCategories.aspx",
    "/Admin/Libraries/Frameworks.aspx",
    "/Admin/Libraries/Components",
    "/Admin/Integration/DataCollection.aspx",
    "/Admin/Integration/DataSources",
    "/Admin/Libraries/GlobalTagLibrary.aspx",
    "/Admin/Integration/DataExports.aspx",
    "/Admin/Reports/Reports.aspx",
    "/Admin/Settings/Managers",
    "/Admin/Settings/PermissionGroups",
    "/Admin/Settings/Domains.aspx",
    "/Admin/Settings/IPRestrictions",
    "/Admin/Settings/CapacityAndTraffic.aspx",
    "/Admin/Settings/SiteConfig",
    "/Admin/Certificate/Csr",
    "/Admin/Certificate/Upload",
    "/Admin/Notifications",
    "/Admin/Settings/ChangePassword",
    "/Admin/Search/Respondents",
    "/Admin/Search/Urls",
    "/Admin/settings/configuration",
    "/Admin/Reports/EditReport.aspx",
    "/admin/campaigns/portfolios.aspx",
    "/admin/campaigns/portfolios.aspx#",
    "/admin/campaigns/portfolios.aspx",
    "/Admin/Libraries/GlobalImageLibrary.aspx",
    "/Admin/Libraries/GlobalFulfillmentLibrary.aspx",
    "/Admin/Libraries/GlobalFormCategories.aspx",
    "/Admin/Libraries/Snippets",
    "/Admin/Libraries/GlobalScriptCategories.aspx",
    "/Admin/Integration/GlobalServerScriptletCategories.aspx",
    "/Admin/Libraries/Widgets",
    "/Admin/Libraries/GlobalEmailTemplateCategories.aspx",
    "/Admin/Libraries/Frameworks.aspx",
    "/Admin/Libraries/Components",
    "/Admin/Integration/DataCollection.aspx",
    "/Admin/Integration/DataSources",
    "/Admin/Libraries/GlobalTagLibrary.aspx",
    "/Admin/Integration/DataExports.aspx",
    "/Admin/Reports/Reports.aspx",
    "/Admin/Settings/Managers",
    "/Admin/Settings/PermissionGroups",
    "/Admin/Settings/Domains.aspx",
    "/Admin/Settings/IPRestrictions",
    "/Admin/Settings/CapacityAndTraffic.aspx",
    "/Admin/Settings/SiteConfig",
    "/Admin/Certificate/Csr",
    "/Admin/Certificate/Upload",
    "/Admin/Notifications",
    "/Admin/Settings/ChangePassword",
    "/Admin/Search/Respondents",
    "/Admin/Search/Urls",
    '/Admin/settings/configuration',
    '/Admin/Libraries/Widgets',
    '/Admin/Libraries/Components',
    '/Admin/Reports/EditReport.aspx',
    '/Admin/Settings/Managers',
    '/Admin/settings/configuration',
    '/Admin/Settings/PermissionGroups',
    '/Admin/Settings/Domains.aspx',
    '/Admin/Settings/IPRestrictions',
    '/Admin/Settings/CapacityAndTraffic.aspx',
    '/Admin/Settings/SiteConfig',
    '/Admin/Certificate/Csr',
    '/Admin/Certificate/Upload',
    // '/Admin/Creative/2',
    // '/Admin/CreativeStudio/6'
    // "/Admin/Logout",

    // "/Admin/Campaigns/Portfolio.aspx?portID=",
    // "/Admin/Campaigns/Campaign.aspx?campID=",
    // "/Admin/Creative/#",
    // "/Admin/Campaigns/PathProof.aspx?campID=&pathID=",
    // "/Admin/Campaigns/PreviewPath.aspx?campID=&pathID=",
    // "/Admin/Campaigns/NewUrl.aspx?campID=&creativeId=",
    // "/Admin/CreativeStudio/",
    // "/Admin/CreativeStudio/",
    // "/Admin/Campaigns/Page//Add",
    // "/Admin/Creative/#del",
    // "/Admin/Campaigns/PathPerf.aspx?campID=&pathID=",
    // "/Admin/Campaigns/EditPath.aspx?campID=&pathID=",
    // "/Admin/Campaigns/Url.aspx?campID=&sid=",
    // "/Admin/Campaigns/Campaign.aspx?campID=#urls",
    // "/Admin/default.aspx",
    // "/admin/default.aspx",
    // "/admin/default.aspx#",
    // "/admin/campaigns/Portfolio.aspx?portID=",
    // "/admin/campaigns/DeletePortfolio.aspx?portID",
    // "/Admin/Default.aspx",
    // "/admin/default.aspx",
    // "/Admin/Campaigns/PathProof.aspx?campID=&pathID=",
    // "/Admin/Campaigns/PreviewPath.aspx?campID=&pathID=",
    // "/Admin/Campaigns/NewUrl.aspx?campID=&creativeId=",
    // "/Admin/CreativeStudio/",
    // "/Admin/CreativeStudio/",
    // "/Admin/Campaigns/Page//Add",
    // "/Admin/Creative/#del",
    // "/Admin/Campaigns/PathPerf.aspx?campID=&pathID=",
    // "/Admin/Campaigns/EditPath.aspx?campID=&pathID=",
    // "/Admin/Campaigns/Url.aspx?campID=&sid=",
    // "/Admin/Campaigns/Campaign.aspx?campID=#urls",
    // '/Admin/default.aspx',
    // "/Admin/Campaigns/Portfolio.aspx?portID=",
    // "/Admin/Campaigns/Campaign.aspx?campID=",
    // "/Admin/Creative/#",
];
